# This is a basic workflow to help you get started with Actions

name: Run Smoke Tests

on: [push]

jobs:
 maestro-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the file
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile
      
        with:
          url: "https://install.appcenter.ms/orgs/sumup/apps/sumup-android-kiwi/distribution_groups/ucars-public"
          target: public/
          # auto-match: true
          filename: downloadfile.apk
          
      - run: maestro cloud downloadfile.apk maestro-end-2-end/
      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: downloadfile.apk
