# This is a basic workflow to help you get started with Actions

name: Run Smoke Tests

on: [push]

jobs:
 maestro-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: suisei-cn/actions-download-file@v1.3.0
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
         url: curl https://install.appcenter.ms/orgs/sumup/apps/sumup-android-kiwi/distribution_groups/ucars-public
         target: public/
         filename: downloadfile.apk

      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: downloadfile.apk
          
      - run: maestro cloud public/downloadfile.apk maestro-end-2-end/
