name: superapp-login

on: workflow_dispatch

env:
  latest_file: "/apk/superapp.zip"

jobs:

  superapp-login-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [fetch_file]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
      - name: copy apk fetch_file
        id: copy apk fetch_file
        run: |
          cp $GITHUB_WORKSPACE/apk/superapp.zip $GITHUB_WORKSPACE/artifacts/$latest_file.zip 

      - name: Install Maestro CLI
        id: install-maestro-cli
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Run tests in Maestro Cloud
        id: run-tests
        run: |
          export PATH="$PATH":"$HOME/.maestro/bin"
          maestro cloud --apiKey ${{ secrets.MAESTRO_CLOUD_KEY }} $GITHUB_WORKSPACE/artifacts/$latest_file.zip super-app/ios-flows